{{- range .Values.operators }}
{{- if .createNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
{{- end }}
{{- end }}
