{{- range .Values.operators }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name | quote }}
  namespace: {{ .namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  name: {{ .name | quote }}
  channel: {{ .channel | quote }}
  source: {{ .source | quote }}
  sourceNamespace: {{ default "openshift-marketplace" .sourceNamespace | quote }}
  installPlanApproval: {{ default "Automatic" .installPlanApproval | quote }}
  {{- if .version }}
  startingCSV: {{ .version | quote }}
  {{- end }}
  {{- if .config }}
  config:
    {{- toYaml .config | nindent 4 }}
  {{- end }}
{{- end }}
